---
- name: config common dir by nfs and mount
  hosts: all
  become: true
  become_user: root
  tasks:
  - name: mount
    mount:
     src: '{{file_path}}'
     path: /nfs
     state: mounted
     boot: yes
     fstype: nfs
    tags:
    - mount

  - name: unmount
    mount:
     path: /nfs
     state: absent
    tags: 
    - unmount

